# Generated by Django 4.1.5 on 2023-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('D', 'Dress'), ('S', 'Shirts'), ('J', 'Jeans'), ('SW', 'Swimwear'), ('SLW', 'Sleepwear'), ('SPW', 'Sportwear'), ('B', 'Blazers'), ('JA', 'Jackets'), ('SH', 'Shoes')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
